cmake_options: -DENABLE_FDB_BUILD_TOOLS=ON
dependencies: |
  ecmwf/ecbuild
  Deutsches-Klimarechenzentrum/libaec@refs/tags/v1.1.6
  ecmwf/eckit@develop
  ecmwf/eccodes
  ecmwf/metkit
  ecmwf/fdb
dependency_branch: develop
parallelism_factor: 8
