cmake_options: -DENABLE_FDB_BUILD_TOOLS=ON 
dependencies: |
  ecmwf/cxx-dependencies@refs/heads/master
  ecmwf/ecbuild
  ecmwf/eccodes
  ecmwf/eckit@develop
  ecmwf/metkit
  ecmwf/fdb
dependency_branch: develop
parallelism_factor: 8
