cmake_options: -DENABLE_FDB_BUILD_TOOLS=ON
dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes
  ecmwf/eckit@develop
  ecmwf/metkit
  ecmwf/fdb
dependency_branch: develop
parallelism_factor: 8
