cmake_options: -DENABLE_FDB_BUILD_TOOLS=ON -DCMAKE_PREFIX_PATH=${CXX-DEPS_DIR} -Dlibaec_ROOT=${CXX-DEPS_DIR}
dependency_cmake_options: |
  ecmwf/eccodes: "-DCMAKE_PREFIX_PATH=${CXX-DEPS_DIR} -Dlibaec_ROOT=${CXX-DEPS_DIR}"
  ecmwf/eckit: "-DCMAKE_PREFIX_PATH=${CXX-DEPS_DIR} -Dlibaec_ROOT=${CXX-DEPS_DIR}"
  ecmwf/metkit: "-DCMAKE_PREFIX_PATH=${CXX-DEPS_DIR}"
  ecmwf/fdb: "-DCMAKE_PREFIX_PATH=${CXX-DEPS_DIR}"
dependencies: |
  ecmwf/ecbuild
  Ozaq/cxx-deps@vendoring
  ecmwf/eccodes
  ecmwf/eckit@develop
  ecmwf/metkit
  ecmwf/fdb
dependency_branch: develop
parallelism_factor: 8
