build:
  python: "3.10"
  modules:
    - ninja
    - cmake/4
  dependencies:
    - ecmwf/ecbuild@develop
    - Ozaq/cxx-deps@vendoring
    - ecmwf/eccodes@develop
    - ecmwf/eckit@develop
    - ecmwf/metkit@develop
    - ecmwf/fdb@develop
    - ecmwf/gribjump@develop
  dependency_cmake_options:
    - 'ecmwf/fdb: -DENABLE_LUSTRE=OFF'
    - 'ecmwf/gribjump: -DENABLE_FDB_BUILD_TOOLS=ON'
  parallel: 64
  env:
    - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
    - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
    - CMAKE_PREFIX_PATH=$TMPDIR/install/cxx-deps/0.0.1
    - libaec_ROOT=$TMPDIR/install/cxx-deps/0.0.1
